// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/travel/:tripId": {
    params: {
      "tripId": string;
    };
  };
  "/create-travel": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/travel/:tripId" | "/create-travel";
  };
  "routes/travel-list.tsx": {
    id: "routes/travel-list";
    page: "/";
  };
  "routes/travel-detail.tsx": {
    id: "routes/travel-detail";
    page: "/travel/:tripId";
  };
  "routes/create-travel.tsx": {
    id: "routes/create-travel";
    page: "/create-travel";
  };
};